apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.config.RABBITMQ_DEFAULT_USER | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.config.RABBITMQ_DEFAULT_PASS | quote }}
