replicaCount: 1

image:
  repository: akhilsurala/webtools-backend
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "webtools-backend-sa"

service:
  type: ClusterIP
  port: 8080


ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: sunseed.local
      paths:
        - path: /api/webtools-backend
          pathType: ImplementationSpecific
  tls: []

resources: {}

#livenessProbe:
 # httpGet:
  #  path: /
   # port: 8080 # The port your application listens on inside the container
  #initialDelaySeconds: 10
  #periodSeconds: 10
  #timeoutSeconds: 5
  #failureThreshold: 3

#readinessProbe:
  #httpGet:
    #path: /
    #port: 8080 # The port your application listens on inside the container
  #initialDelaySeconds: 5
  #periodSeconds: 10
  #timeoutSeconds: 5
  #failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

configmap:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sunseed
  SPRING_PROFILES_ACTIVE: dev
  CROP_INTERVALTYPE: "1"

secrets:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: newlife
