apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webtool-authorization.fullname" . }}-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.SPRING_DATASOURCE_PASSWORD | quote }}
  JWT_SECRET_KEY: {{ .Values.secret.JWT_SECRET_KEY | quote }}
