apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sunseed-simtool.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
