# Default values for webtool-authorization.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: akhilsurala/webtool-authorization
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "authorization-sa"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8081


ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: sunseed.local
      paths:
        - path: /api/authorization
          pathType: ImplementationSpecific
  tls: []

resources: {}
livenessProbe:
  httpGet:
    path: /
    port: 8081 # The port your application listens on inside the container
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 8081 # The port your application listens on inside the container
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

configmap:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users
  SPRING_DATASOURCE_USERNAME: postgres
  JWT_TOKEN_EXPIRATION_TIME: "604800000"
  SPRING_PROFILES_ACTIVE: dev

secret:
  SPRING_DATASOURCE_PASSWORD: newlife
  JWT_SECRET_KEY: 5A7134743777397A24432646294A404E635266556A586E3272357538782F4125
