export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const SET_SIMULATION_GROUND_AREA = "SET_SIMULATION_GROUND_AREA";
export const SET_CURRENT_SELECTED_RUN = "SET_CURRENT_SELECTED_RUN";
export const SET_RUN_OPTIONS = "SET_RUN_OPTIONS";
export const SET_URL_DETAILS="SET_URL_DETAILS"
export const SET_URL_DETAILS_WEEK_TIME="SET_URL_DETAILS_WEEK_TIME"
export const UPDATE_MIN_MAX_FOR_3D_VIEWER="UPDATE_MIN_MAX_FOR_3D_VIEWER"