
export const SET_APV_TOGGLE = 'SET_APV_TOGGLE';
export const SET_PROJECT_NAME = 'SET_PROJECT_NAME';
export const SET_RUN_ID = 'SET_RUN_ID'
export const UPDATE_FORM_VALUE = 'UPDATE_FORM_VALUE';
export const SET_PV_PARAMETERS = 'SET_PV_PARAMETERS';
export const SELECTED_RUN_TYPE = "SELECTED_RUN_TYPE";
export const SET_PV_PARAMETER_DETAILS = 'SET_PV_PARAMETER_DETAILS';
