replicaCount: 1

image:
  repository: akhilsurala/postgres
  pullPolicy: Always
  tag: "15"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5432

resources: {}

livenessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# ✅ Persistent storage for PostgreSQL data
persistence:
  enabled: true
  storageClassName: standard  # adjust based on your environment, or leave empty for default
  accessModes:
    - ReadWriteOnce
  size: 1Gi

volumes:
  - name: pgdata
    persistentVolumeClaim:
      claimName: postgres-dev-pvc

volumeMounts:
  - name: pgdata
    mountPath: /var/lib/postgresql/data

nodeSelector: {}

tolerations: []

affinity: {}

config:
  POSTGRES_USER: postgres

secret:
  POSTGRES_PASSWORD: newlife
