apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sunseed-frontend-hpa
  namespace: sunseed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sunseed-frontend-deployment-blue
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
