apiVersion: v1
kind: Secret
metadata:
  name: sunseed-secrets
  namespace: sunseed
type: Opaque
stringData:
  POSTGRES_PASSWORD: newlife
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
  SPRING_MAIL_PASSWORD: nropqhwgjjhnbrns
  JWT_SECRET_KEY: 5A7134743777397A24432646294A404E635266556A586E3272357538782F4125
  JWT_TOKEN_EXPIRATION_TIME: "604800000"
