apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtool-mailservice
  namespace: sunseed
  labels:
    app: mailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailservice
  template:
    metadata:
      labels:
        app: mailservice
    spec:
      containers:
      - name: webtool-mailservice
        image: akhilsurala/webtool-mailservice:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_MAIL_USERNAME
          value: sunseedapv@gmail.com
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sunseed-secrets
              key: SPRING_MAIL_PASSWORD
        - name: SPRING_MAIL_HOST
          value: smtp.gmail.com
        - name: SPRING_MAIL_PORT
          value: "587"
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
          value: "true"
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
          value: "true"
        - name: SPRING_PROFILES_ACTIVE
          value: dev
