
ALTER TABLE agri_general_parameter
    ALTER COLUMN trail TYPE DOUBLE PRECISION USING trail::DOUBLE PRECISION,
    ALTER COLUMN min_temp TYPE DOUBLE PRECISION USING min_temp::DOUBLE PRECISION,
    ALTER COLUMN max_temp TYPE DOUBLE PRECISION USING max_temp::DOUBLE PRECISION;


ALTER TABLE bed_parameter
    ALTER COLUMN bed_angle TYPE DOUBLE PRECISION USING bed_angle::DOUBLE PRECISION,
    ALTER COLUMN bed_azimuth TYPE DOUBLE PRECISION USING bed_azimuth::DOUBLE PRECISION,
    ALTER COLUMN start_point_offset TYPE DOUBLE PRECISION USING start_point_offset::DOUBLE PRECISION;

ALTER TABLE agri_pv_protection_height
    ALTER COLUMN protection_height TYPE DOUBLE PRECISION USING protection_height::DOUBLE PRECISION;


ALTER TABLE economic_parameters
    ALTER COLUMN hourly_selling_rates TYPE DOUBLE PRECISION[]
    USING hourly_selling_rates::DOUBLE PRECISION[];