CREATE TABLE if not exists optical_property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transmission_nir DOUBLE PRECISION,
    reflection_nir DOUBLE PRECISION ,
    transmission_par DOUBLE PRECISION ,
    reflection_par DOUBLE PRECISION ,
    optical_property_file VARCHAR(255)
);

-- Add the optical_property_id column to the crops table
ALTER TABLE crop
ADD COLUMN optical_property_id BIGINT;

-- Add a foreign key constraint linking crops to optical_property
ALTER TABLE crop
ADD CONSTRAINT fk_crops_optical_property
    FOREIGN KEY (optical_property_id)
    REFERENCES optical_property(id)
    ON DELETE SET NULL;
    
CREATE TABLE if not exists stomatal_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    em DOUBLE PRECISION NOT NULL,
    io DOUBLE PRECISION NOT NULL,
    k DOUBLE PRECISION NOT NULL,
    b DOUBLE PRECISION NOT NULL
);

-- Add the optical_property_id column to the crops table
ALTER TABLE crop
ADD COLUMN stomatal_parameter_id BIGINT;

-- Add a foreign key constraint linking crops to optical_property
ALTER TABLE crop
ADD CONSTRAINT fk_crops_stomatal_parameter
    FOREIGN KEY (stomatal_parameter_id)
    REFERENCES stomatal_parameter(id)
    ON DELETE SET NULL;

    
CREATE TABLE if not exists farquhar_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vc_max DOUBLE PRECISION NOT NULL,
    j_max DOUBLE PRECISION NOT NULL,
    cj_max DOUBLE PRECISION NOT NULL,
    ha_j_max DOUBLE PRECISION NOT NULL,
    alpha DOUBLE PRECISION NOT NULL,
    rd_25 DOUBLE PRECISION NOT NULL
);

-- Add the optical_property_id column to the crops table
ALTER TABLE crop
ADD COLUMN farquhar_parameter_id BIGINT;

-- Add a foreign key constraint linking crops to optical_property
ALTER TABLE crop
ADD CONSTRAINT fk_crops_farquhar_parameter
    FOREIGN KEY (farquhar_parameter_id)
    REFERENCES farquhar_parameter(id)
    ON DELETE SET NULL;
    
ALTER TABLE crop
ADD COLUMN required_dli BIGINT ,
ADD COLUMN required_ppfd BIGINT ,
ADD COLUMN harvest_days BIGINT ,
ADD COLUMN f1 DOUBLE PRECISION,
ADD COLUMN f2 DOUBLE PRECISION,
ADD COLUMN f3 DOUBLE PRECISION,
ADD COLUMN f4 DOUBLE PRECISION,
ADD COLUMN f5 DOUBLE PRECISION;
    
