apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webtools-backend.fullname" . }}-secret
  labels:
    {{- include "webtools-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
