name: Deploy to Minikube

on:
  push:
    branches:
      - master   # Trigger on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo to access deployment.yaml
      - name: Checkout repo
        uses: actions/checkout@v3

      # Install kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.34.0'   

      # Configure kubeconfig (from GitHub secret)
      - name: Configure Minikube Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_MINIKUBE }}" > $HOME/.kube/config

      # Apply deployment file (from repo path)
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f sunseed/sunseed-frontend/deployment.yaml
          kubectl rollout status deployment/myapp-deployment
 




