name: Deploy to EKS

on:
  push:
    branches:
      - master   # or main, depending on your repo
  workflow_dispatch: # allows you to trigger manually from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name eks-fargate-cluster

      - name: Deploy to EKS
        run: kubectl apply -f Sunseed/sunseed-frontend/deployment.yaml

    


   

   
 




