apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webtool-mailservice.fullname" . }}-secret
  labels:
    {{- include "webtool-mailservice.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
